In [3]:
import numpy as np

In [4]:
a = np.array([[1,1,1],[2,2,2],[3,3,3]])
b = np.array([[1,1,1], [5,5,5]])

In [5]:
for i in range(a.shape[0]):
    for j in range(b.shape[0]):
        print np.sqrt(np.sum(((a[i] - b[j])**2)))

0.0
6.92820323028
1.73205080757
5.19615242271
3.46410161514
3.46410161514


In [6]:
np.sum(np.square(b[0] - a),axis=1)

array([ 0,  3, 12])

In [7]:
print b.shape,a.shape
np.sqrt(np.sum(np.square(np.subtract(b[0] a),axis=1))

(2, 3) (3, 3)


array([ 0.        ,  1.73205081,  3.46410162])

In [10]:
from numpy import newaxis
np.transpose(np.sqrt(np.sum(np.square(np.subtract(b, a[:,newaxis])),axis=2)))

array([[ 0.        ,  1.73205081,  3.46410162],
       [ 6.92820323,  5.19615242,  3.46410162]])

In [25]:
2 * b.dot(a)

array([[12, 12, 12],
       [60, 60, 60]])

In [33]:
print np.tile(b,1)
np.tile(a,b.shape)
a**2 + np.tile(b,a.shape) **2

[[1 1 1]
 [5 5 5]]


ValueError: operands could not be broadcast together with shapes (3,3) (6,9) 

In [40]:
print np.tile(b,(:,1))
print b

SyntaxError: invalid syntax (<ipython-input-40-cb69822ee5bd>, line 1)