In [1]:
import numpy as np

In [29]:
a = np.array([[1,1,1],[2,2,2],[3,3,3]])
b = np.array([[1,1,1], [5,5,5]])
print a
print b

[[1 1 1]
 [2 2 2]
 [3 3 3]]
[[1 1 1]
 [5 5 5]]


In [105]:
# print np.diag(a.dot(a.T)).dot(np.ones((b.shape[0],1)))
# print np.ones((a.shape[0],1)).dot(np.diag(b.dot(b.T)))
# print 2 * b.dot(a.T)
print b.shape, a.shape
b2 = np.diag(b.dot(b.T))
b2 = b2.reshape(b2.shape[0],1)
a2 = np.diag(a.dot(a.T))
a2 = a2.reshape(a2.shape[0],1)
print "initial shapes without adding ones"
print b2.shape, a2.shape
b2new = b2.dot(np.ones((1,a.shape[0])))
print "shapes after adding ones"
print b2new.shape
a2new = np.ones((b.shape[0],1)).dot(a2.T)
print b2new.shape,a2new.shape
print b2new
print "-----------"
print a2new
print "--------------"
print 2 * b.dot(a.T)
print b2new + a2new - (2 * b.dot(a.T))

(2, 3) (3, 3)
initial shapes without adding ones
(2, 1) (3, 1)
shapes after adding ones
(2, 3)
(2, 3) (2, 3)
[[  3.   3.   3.]
 [ 75.  75.  75.]]
-----------
[[  3.  12.  27.]
 [  3.  12.  27.]]
--------------
[[ 6 12 18]
 [30 60 90]]
[[  0.   3.  12.]
 [ 48.  27.  12.]]


In [100]:
for i in range(a.shape[0]):
    for j in range(b.shape[0]):
        print a[i],b[j]
        print "--------"
        print np.sum(((a[i] - b[j])**2))
        print "----------"
        print np.sqrt(np.sum(((a[i] - b[j])**2)))

[1 1 1] [1 1 1]
--------
0
----------
0.0
[1 1 1] [5 5 5]
--------
48
----------
6.92820323028
[2 2 2] [1 1 1]
--------
3
----------
1.73205080757
[2 2 2] [5 5 5]
--------
27
----------
5.19615242271
[3 3 3] [1 1 1]
--------
12
----------
3.46410161514
[3 3 3] [5 5 5]
--------
12
----------
3.46410161514


In [4]:
np.sum(np.square(b[0] - a),axis=1)

array([ 0,  3, 12])

In [5]:
print b.shape,a.shape
np.sqrt(np.sum(np.square(np.subtract(b[0] a),axis=1))

SyntaxError: invalid syntax (<ipython-input-5-4bca7a4c0fd9>, line 2)

In [6]:
from numpy import newaxis
np.transpose(np.sqrt(np.sum(np.square(np.subtract(b, a[:,newaxis])),axis=2)))

array([[ 0.        ,  1.73205081,  3.46410162],
       [ 6.92820323,  5.19615242,  3.46410162]])

array([[12, 12, 12],
       [60, 60, 60]])

In [8]:
print np.tile(b,1)
np.tile(a,b.shape)
a**2 + np.tile(b,a.shape) **2

[[1 1 1]
 [5 5 5]]


ValueError: operands could not be broadcast together with shapes (3,3) (6,9) 

In [21]:
print b.shape, a.shape
np.diag((b * b.transpose()))

(2, 3) (3, 3)


ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [27]:
    print b.dot(b.transpose()), b.dot(b.transpose()).shape
    print a.transpose().dot(a), a.transpose().dot(a).shape
    print np.diag(b.dot(b.transpose()))np.ones(, np.diag(a.transpose().dot(a))

[[ 3 15]
 [15 75]] (2, 2)
[[14 14 14]
 [14 14 14]
 [14 14 14]] (3, 3)
[ 3 75] [14 14 14]


In [28]:
b.transpose().dot(b)

array([[26, 26, 26],
       [26, 26, 26],
       [26, 26, 26]])

In [118]:
print b
print "-----"
print a[1:,:]

[[1 1 1]
 [5 5 5]]
-----
[[2 2 2]
 [3 3 3]]


In [116]:
np.concatenate((b,a[1:,:]),axis=0)

array([[1, 1, 1],
       [5, 5, 5],
       [2, 2, 2],
       [3, 3, 3]])